#TargetMkt.Domain.Entity.Customer.dcm.yml
TargetMkt\Domain\Entity\Customer:
  type: entity
  repositoryClass: TargetMkt\Infrastructure\Persistence\Doctrine\Repository\CustomerRepository
  table: customers
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      unique: true